from dataclasses import dataclass
from datetime import date, time, datetime
from typing import Optional


# =========================
# STUDENT MODEL
# =========================
@dataclass
class Student:
    id: Optional[int]
    student_code: str
    name: str
    face_encoding: object
    """
    Represents a student registered in the system.
    face_encoding: numpy array or list generated by face recognition library
    """


# =========================
# INSTRUCTOR MODEL
# =========================
@dataclass
class Instructor:
    id: Optional[int]
    name: str
    email: str
    """
    Represents an instructor who conducts lecture sessions.
    """


# =========================
# LECTURE / SESSION MODEL
# =========================
@dataclass
class Lecture:
    id: Optional[int]
    instructor_id: int
    course_name: str
    room: str
    session_date: date
    start_time: time
    end_time: time
    """
    Represents a single lecture/session.
    Linked to an instructor and used for attendance tracking.
    """


# =========================
# ATTENDANCE MODEL
# =========================
@dataclass
class Attendance:
    id: Optional[int]
    lecture_id: int
    student_id: int
    attendance_time: datetime
    status: str = "Present"
    """
    Represents one attendance record.
    status: Present / Late
    """


# =========================
# REPORT MODELS (Optional but Recommended)
# =========================
@dataclass
class StudentAttendanceReport:
    student_code: str
    student_name: str
    course_name: str
    session_date: date
    status: str


@dataclass
class LectureAttendanceReport:
    student_code: str
    student_name: str
    attendance_time: datetime
    status: str
